name: Copy To ADLS
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Select environment'     
        required: true
        default: 'dev'
      folder:
        description: 'Input folder to copy e.g. folder1/folder2/folder3'
        required: true
        default: 'folder1'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      ENV_PREFIX: ${{ vars.ENV_PREFIX }}
      CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
      STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}
      STG_STORAGE_ACCOUNT_NAME: ${{ vars.STG_STORAGE_ACCOUNT_NAME }}
      DEST_FOLDER_PATH: app1/${{ vars.ENV_PREFIX }}/${{ github.event.inputs.folder }}
      SRC_FOLDER_PATH: ${{ github.event.inputs.folder }}
    steps:
      - name: Set variables
        run: |
          echo "Folder Input: ${{ github.event.inputs.folder }}"
          echo "Storage Account Name: $STORAGE_ACCOUNT_NAME"
          echo "Container Name: $CONTAINER_NAME"
          echo "Dest Folder Path: $DEST_FOLDER_PATH"
          echo "Source Folder Path: $SRC_FOLDER_PATH"
          echo az storage blob upload-batch --destination "https://$STG_STORAGE_ACCOUNT_NAME.blob.core.windows.net/$CONTAINER_NAME" --destination-path $DEST_FOLDER_PATH --source "$SRC_FOLDER_PATH" --pattern "*"
          echo az storage blob copy start-batch --account-name $STORAGE_ACCOUNT_NAME --destination-container $CONTAINER_NAME --destination-path $DEST_FOLDER_PATH --source-account-name $STG_STORAGE_ACCOUNT_NAME --source-container $CONTAINER_NAME --pattern $DEST_FOLDER_PATH/*
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Copy folder to ADLS stage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
            --destination "https://$STG_STORAGE_ACCOUNT_NAME.blob.core.windows.net/$CONTAINER_NAME" \
            --destination-path $DEST_FOLDER_PATH \
            --source "$SRC_FOLDER_PATH" \
            --pattern "*" 
      - name: Copy folder to ADLS
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob copy start-batch \
            --account-name $STORAGE_ACCOUNT_NAME \
            --destination-container $CONTAINER_NAME \
            --destination-path $DEST_FOLDER_PATH \
            --source-account-name $STG_STORAGE_ACCOUNT_NAME \
            --source-container $CONTAINER_NAME \
            --pattern $DEST_FOLDER_PATH/*
      - name: Logout
        run: |
            az logout
        if: always()

